@startuml use_cases
!theme mono
skinparam dpi 150
left to right direction

actor Usuário

rectangle "Ferramenta de Framework Semiótico ES" {
    (RF01 - Visualizar Perguntas) as visualizar
    (RF02 - Responder Pergunta) as responder
    (RF03 - Visualizar Perguntas Agrupadas) as agrupar
    (RF04 - Importar Arquivos XML) as importar
    (RF05 - Exportar Arquivo XML com respostas) as salvar
    (RF06 - Exportar documento com elementos dispostos nas Camadas da Engenharia de Software) as camadas
    (RF07 - Exportar documento com checklist) as checklist
    (RF08 - Exportar documento com elementos dispostos na Escada Semiótica) as escada
}

Usuário --> visualizar
Usuário --> responder
Usuário --> agrupar
Usuário --> importar
Usuário --> salvar
Usuário --> camadas
Usuário --> checklist
Usuário --> escada

@enduml
